### ISSUE TITLE
the role does not support CentOS

### ISSUE THREAD

**Issue by mitsururike** [reallyenglish/ansible-role-vagrant#3]
no yum repository.
rpm is available on the official site.

**Comment by trombik** [comment]
in general, the package should be installed in the order from:

* the official OS distribution repository, CentOS repo
* the semi-official repository, EPEL and PPA for example
* the official vendor's repository, hashicorp in this case
* Reallyenglish repository
 
packages must not be installed from unknown sources, or unofficial repositories
